apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ci-helper-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ci-helper-app
    app.kubernetes.io/part-of: ci-helper-app
  name: ci-helper-app
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: ci-helper-app
status:
  loadBalancer: {}
